<a href="https://colab.research.google.com/github/tejasabert/NHANES_FTI/blob/main/TejasAbert_NHANESFTI_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [10]:
df = pd.read_csv("health_and_nutrition_women_export.csv")
df.head()

,Unnamed: 0,SEQN,RIAGENDR,RIDRETH3,RIDAGEYR,BMXHT,BMXBMI,BMXWT,BMXWAIST,RIDEXPRG,WTMEC2YR,WTMEC4YR,combinedWeight
0,4,83735,2,3,56,1609.0,42.4,109.8,1101.0,NaN,102078.634508,NaN,51039.317254
1,6,83737,2,1,72,1500.0,28.6,64.4,929.0,NaN,10878.684022,NaN,5439.342011
2,11,83742,2,1,32,1513.0,28.2,64.5,933.0,2.0,23557.163453,NaN,11778.581727
3,21,83752,2,1,30,1636.0,26.6,71.2,907.0,2.0,38680.531261,NaN,19340.265630
4,23,83754,2,1,67,1641.0,43.7,117.8,1230.0,NaN,10191.914345,NaN,5095.957172

In [9]:
df = pd.read_csv("health_and_nutrition_combined_clean.csv")
df.head()

,Unnamed: 0,SEQN,RIAGENDR,RIDRETH3,RIDAGEYR,BMXHT,BMXBMI,BMXWT,RIDEXPRG,WTMEC4YR
0,0,83732,1,3,62,1845.0,27.8,94.8,NaN,NaN
1,1,83733,1,3,53,1714.0,30.8,90.4,NaN,NaN
2,2,83734,1,3,78,1701.0,28.8,83.4,NaN,NaN
3,3,83741,1,4,22,1654.0,28.0,76.6,NaN,NaN
4,4,83744,1,4,56,1794.0,33.6,108.3,NaN,NaN

In [8]:
df = pd.read_csv("health_and_nutrition_men_export.csv")
df.head()

,Unnamed: 0,SEQN,RIAGENDR,RIDRETH3,RIDAGEYR,BMXHT,BMXBMI,BMXWT,BMXWAIST,RIDEXPRG,WTMEC2YR,WTMEC4YR,combinedWeight
0,1,83732,1,3,62,1845.0,27.8,94.8,1011.0,NaN,135629.507405,NaN,67814.753703
1,2,83733,1,3,53,1714.0,30.8,90.4,1079.0,NaN,25282.425927,NaN,12641.212964
2,3,83734,1,3,78,1701.0,28.8,83.4,1165.0,NaN,12575.838818,NaN,6287.919409
3,10,83741,1,4,22,1654.0,28.0,76.6,866.0,NaN,39353.307397,NaN,19676.653698
4,13,83744,1,4,56,1794.0,33.6,108.3,1160.0,NaN,20068.662891,NaN,10034.331445